version: '2.4'
volumes:
  logs: {}
  config: {}
  data: {}
  wheel-cache: {}
  telegraf-state: {}

services:
  # bluetooth:
  #   image: bh.cr/balenalabs/bluetooth-rpi
  #   labels:
  #     io.balena.features.dbus: '1'
  #   cap_add:
  #     - NET_ADMIN
  #   restart: on-failure
  #   network_mode: host

  smartsolar:
    build: ./smartsolar
    # depends_on:
    #   - bluetooth
    restart: on-failure
    environment:
      - TZ=UTC
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      # Timing configuration (optional)
      - BLE_SCAN_TIMEOUT=5      # Max seconds to scan for device (1-30, default: 5)
      - COLLECTION_INTERVAL=60  # Seconds between collections (min: 10, default: 60)
    volumes:
      - logs:/var/log
      - data:/data
      - wheel-cache:/wheel-cache
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
  
  shelly:
    build: ./shelly
    restart: on-failure
    environment:
      - TZ=UTC
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      # Shelly device configuration
      - SHELLY_MAC=A0:DD:6C:4B:9C:36
      - SHELLY_SCAN_INTERVAL=30
    volumes:
      - logs:/var/log
      - data:/data
      - wheel-cache:/wheel-cache
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
  
  telegraf:
    build: ./telegraf
    restart: always
    environment:
      # InfluxDB Cloud Configuration
      - INFLUX_URL=https://eu-central-1-1.aws.cloud2.influxdata.com
      - INFLUX_TOKEN
      - INFLUX_ORG
      - INFLUX_BUCKET=smartsolar
      # Balena device name for hostname
      - BALENA_DEVICE_NAME_AT_INIT
    volumes:
      # Read-only access to data files
      - data:/data:ro
      # Persistent state for Telegraf
      - telegraf-state:/var/lib/telegraf
    depends_on:
      - smartsolar
      - shelly
    labels:
      io.balena.features.balena-api: '1'
  